In [10]:
install = False 
if install:
    !pip3 install opencv-python
    !pip3 install numpy

import numpy as np
import cv2 
import os 
import glob

In [2]:
# ensure image directory is made and lables in directories
!mkdir -p greyAndEquPalm/test
!mkdir -p greyAndEquPalm/train
moveDoc = False 
if moveDoc:
    !cp -v palm/*.csv greyAndEquPalm/
    !cp -v palm/test/*.xml greyAndEquPalm/test
    !cp -v palm/train/*.xml greyAndEquPalm/train
check1 = True 
if check1:
    print("original test xml")
    !ls -l palm/test/*.xml | wc -l
    print("new test xml")
    !ls -l greyAndEquPalm/test/*.xml | wc -l
    print("original train xml")
    !ls -l palm/train/*.xml | wc -l
    print("new train xml")
    !ls -l greyAndEquPalm/train/*.xml | wc -l

original test xml
      70
new test xml
      70
original train xml
     279
new train xml
     279


In [ ]:

    
    #turn grey and equalize 
    # TODO: rgb to grey , query picture , provs better z normalsation 
    # keep clustering on own laptop 
    # consider pca projection in speed up graph 


In [7]:
"""src refers to the path/to/files/*.extention where all the images are 
    dest refers to the destination in which the processessed images are saved
    dest str must end with / bcs of implementation of function 
    verbose = True prints out all the images as they are saved"""
def greyAndEqu(src, dest, verbose = False):
    # list of test image paths for .jpeg
    testIm_paths = glob.glob(src)   

    # for the test set 
    for im_path in testIm_paths:
        im = cv2.imread(im_path)

        # check if successfully read 
        if im is None:
            print(f"Error reading image {im_path}")
            continue
        
        #turn grey and equalize 
        #when turing grey scale, the rabe is [0,255]
        #grey_im = cv2.cvtColor(im, cv2.COLOR_RGB2GRAY)
        equ_im = cv2.equalizeHist(im)

        # Extract the image file name
        im_name = os.path.basename(im_path)

        output_path = os.path.join(dest, im_name)
        
        # Save the grayscale, equalised image
        cv2.imwrite(output_path, equ_im)
        if verbose:
            print(f'Saved grayscale image: {output_path}')
    
    print("All images processed and saved!")

notDone = True 
if notDone:
    #greyAndEqu("palm/test/ck2euxc9kxgvm07486g2d5pid.jpg", "greyAndEquPalm/")
    # for the test set 
    greyAndEqu("palm/test/*.jp*", "greyAndEquPalm/test/")

    # for the train set 
    greyAndEqu("palm/train/*.jp*", "greyAndEquPalm/train/")

All images processed and saved!
All images processed and saved!


In [8]:
check2 = True 
if check2:
    print("test xml") # images must match amount of xml 
    !ls -l palm/test/*.xml | wc -l
    print("test image")
    !ls -l greyAndEquPalm/test/*.jp* | wc -l
    print("train xml") # images must match amount of xml 
    !ls -l palm/train/*.xml | wc -l
    print("train image")
    !ls -l greyAndEquPalm/train/*.jp* | wc -l

test xml
      70
test image
      70
train xml
     279
train image
     279


In [18]:
# testing only for one image 

im_path = "/Users/catherineli/Library/CloudStorage/OneDrive-UniversityofCapeTown/2.CSC2005Z/code-related/palm/test/ck2euxc9kxgvm07486g2d5pid.jpg"
im = cv2.imread(im_path)

# check if successfully read 
if im is not None:
    
    #turn grey and equalize 
    #when turing grey scale, the rabe is [0,255]
    grey_im = cv2.cvtColor(im, cv2.COLOR_RGB2GRAY)
    equ_im = cv2.equalizeHist(grey_im)
    print(grey_im.ndim)
    print(grey_im)

    output_path = "/Users/catherineli/Library/CloudStorage/OneDrive-UniversityofCapeTown/2.CSC2005Z/test.jpg"

    # Save the grayscale, equalised image
    cv2.imwrite(output_path, equ_im)

    print(f'Saved grayscale image: {output_path}')

else:
    print(f"Error reading image {im_path}")


2
[[102  94  87 ... 208 210 204]
 [104  90  78 ... 208 210 205]
 [106  91  81 ... 211 212 208]
 ...
 [ 79  87  94 ... 223 223 223]
 [ 81  93 101 ... 223 223 223]
 [ 94  97  95 ... 223 223 223]]
Saved grayscale image: /Users/catherineli/Library/CloudStorage/OneDrive-UniversityofCapeTown/2.CSC2005Z/test.jpg
