In [2]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
import glob

In [3]:
image = cv2.imread("/Users/catherineli/Library/CloudStorage/OneDrive-UniversityofCapeTown/2.CSC2005Z/code-related/singleTree/test/ck2euxc9kxgvm07486g2d5pid_0_2492_267_2848_Palm.jpg", flags = cv2.IMREAD_GRAYSCALE)
imageN =cv2.imread("/Users/catherineli/Library/CloudStorage/OneDrive-UniversityofCapeTown/2.CSC2005Z/code-related/singleTree/test/norm/ck2euxc9kxgvm07486g2d5pid_0_2492_267_2848_Palm.jpg", flags = cv2.IMREAD_GRAYSCALE)

tree_im = cv2.imread("/Users/catherineli/Library/CloudStorage/OneDrive-UniversityofCapeTown/2.CSC2005Z/code-related/singleTree/test/ck2euxc9kxgvm07486g2d5pid_33_1251_339_1622_Tree.jpg", flags = cv2.IMREAD_GRAYSCALE)
tree_imN = cv2.imread("/Users/catherineli/Library/CloudStorage/OneDrive-UniversityofCapeTown/2.CSC2005Z/code-related/singleTree/test/norm/ck2euxc9kxgvm07486g2d5pid_33_1251_339_1622_Tree.jpg", flags = cv2.IMREAD_GRAYSCALE)
print(imageN)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]


In [ ]:
# def histo(image):
#     histogram = np.array(cv2.calcHist([image], [0], None, [256], [0, 256]))

#     # show the histogram
#     plt.hist(histogram, bins=30, edgecolor='black')
#     plt.title("Grayscale Histogram")
#     plt.xlabel("Pixel Intensity")
#     plt.ylabel("Frequency")
#     plt.xlim([0, 256])  # Pixel intensity ranges from 0 (black) to 255 (white)

#     # Display the plot
#     plt.show()

# def histoN(image):
#     histogram = np.array(cv2.calcHist([image], [0], None, [256], [-3, 3]))

#     # show the histogram
#     plt.hist(histogram, bins=30, edgecolor='black')
#     plt.title("Grayscale Histogram")
#     plt.xlabel("Pixel Intensity")
#     plt.ylabel("Frequency")
#     plt.xlim([-3, 3])  # Pixel intensity ranges from 0 (black) to 255 (white)

#     # Display the plot
#     plt.show()


# # code histogrdam 
#     # (x-m)/distance of bin
#     # inspec each iange to find correct lower bound and upper bound 
#     # histogram list initialised to 0 
#     # hve to normalise to probability (map into 0 to 1)     

# histo(image)
# histoN(imageN)
# histo(tree_im)
# histoN(tree_imN)

In [4]:

def hist_feature(image):
    flattened = image.ravel()
    max = float(flattened.max()+1)
    min = float(flattened.min())
    
    # n_bins = int(max-min)

    hist, bin_edges = np.histogram(flattened, bins=32, range=(min,max), density=True)
    # print("fattened image array ",flattened)
    # print("length of image: ",len(flattened))
    # print("max ", max, "\nmin ", min)
    # print("Histogram values with density True: ",hist)
    # print('histogram edges: ', bin_edges)

    plot = False
    if plot:
        # Plot the histogram
        plt.hist(flattened, bins=bin_edges, range=(min, max), density=True, facecolor='0.5')
        plt.title("Histogram")
        plt.xlabel("Value")
        plt.ylabel("Frequency")
        plt.show()
    # convert to histogram 
    #return hist, bin_edges
    return hist

# Store all the feature vectors into dictionary
# takes in the directory of the single trees 
# returns a dictionary of hist features 
def extractHist(srcDir):
    
    hist_dict = {}
    im_paths = glob.glob(srcDir+"*.j*" )
    len_dir = len(srcDir)
    # print(len_dir)
    
    # for each tree extract hist feature 
    for im_path in im_paths:
        
        image = cv2.imread(im_path, flags = cv2.IMREAD_GRAYSCALE)
            
        # find name of corresponding image (watch out if file name has a .j in other places)
        dot_index = im_path.find(".j")
        im_name = im_path[len_dir:dot_index]
        np_hist = hist_feature(image)
        hist_dict[im_name] = np_hist


    return hist_dict


2669
10398


In [5]:
generateFeatures = True
if generateFeatures:
    hist_dict_test = extractHist("/Users/catherineli/Library/CloudStorage/OneDrive-UniversityofCapeTown/2.CSC2005Z/code-related/singleTree/test/")
    print(len(hist_dict_test))
    hist_dict_testN = extractHist("/Users/catherineli/Library/CloudStorage/OneDrive-UniversityofCapeTown/2.CSC2005Z/code-related/singleTree/test/norm/")

    hist_dict_train = extractHist("/Users/catherineli/Library/CloudStorage/OneDrive-UniversityofCapeTown/2.CSC2005Z/code-related/singleTree/train/")
    print(len(hist_dict_train))
    hist_dict_trainN = extractHist("/Users/catherineli/Library/CloudStorage/OneDrive-UniversityofCapeTown/2.CSC2005Z/code-related/singleTree/train/norm/")
    
    np.save('hist_test.npy', hist_dict_test)
    np.save('hist_train.npy', hist_dict_train)

    dict = hist_dict_train | hist_dict_test
    np.save('hist.npy', dict)
    
    np.save('hist_testN.npy', hist_dict_testN)
    np.save('hist_trainN.npy', hist_dict_trainN)

    dict = hist_dict_trainN | hist_dict_testN
    np.save('hist_n.npy', dict)

2669
10398
